ApiVersion: v1
Data: null
Kind: ConfigMap
Metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":null,"labels":{"app.kubernetes.io/name":"argocd-gpg-keys-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-gpg-keys-cm","namespace":"argocd"}}\n'
  creationTimestamp: "2023-11-22T06:06:21Z"
  labels:
    app.kubernetes.io/name: argocd-gpg-keys-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-gpg-keys-cm
  namespace: argocd
  resourceVersion: "176619815"
  uid: 7c741ba5-9292-4a82-a226-6d062db8d6c2
Name: argocd-gpg-keys-cm
metadata:
  resourceVersion: testing
